language: ruby
rvm:
- 2.3.1

before_script:
  # install Gulp 4 CLI tools globally from 4.0 GitHub branch
  - npm install skeleton-sass-official

cache: bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rake publish

git:
  depth: 1
