language: ruby
rvm:
- 2.3.1

before_script:
  - npm install

cache:
  bundler: true
  directories:
    - node_modules

script: rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rake publish

git:
  depth: 1

notifications:
  email: false
  slack:
    rooms:
      - checkhealth:<%= ENV['SLACK_TOKEN'] %>
    on_success: always
