# Site settings
title: The Medical Toolkit
email: bdbaruah@orthodoc.in
description: A Doctor's Ultimate Survival Guide in the Digital Space
logo: "/assets/images/logo.png"
baseurl: ""
url: "https://themedicaltoolkit.com"

name: 'Dr. Biswajit Baruah'
bio: >
  Hip Replacement Surgeon from Chennai.
  Developer of Diagnox mobile app.
  Wannabe long distance runner.
author_image: "/assets/images/author.png"
twitter_username: 0rthodoc
github_username:  orthodoc

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  courses:
    output: true
    permalink: /courses/:path/
    title: Courses
  articles:
    output: true
    permalink: /articles/:path/
    title: Articles
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website_sample.yml
  - s3_website.yml
  - License
  - README.md
  - node_modules
  - package.json
  - index_old.html
  - Rakefile
  - vendor

# seo
author: Dr Biswajit Baruah
twitter:
  username: 0rthodoc
facebook:
  publisher: medtoolkit
social:
  name: Dr Biswajit Baruah
  links:
    - https://twitter.com/0rthodoc
    - https://facebook.com/medtoolkit
    - https://in.linkedin.com/in/bdbaruah
    - https://plus.google.com/communities/112396621505218434918
    - https://github.com/orthodoc

# Google settings
google:
  tag_manager:
    container_id: GTM-N7B9NJN
  analytics:
    id: UA-88248597-1
